/* ydtcpdetail.h generated by valac 0.22.1, the Vala compiler, do not modify */


#ifndef __YDTCPDETAIL_H__
#define __YDTCPDETAIL_H__

#include <glib.h>
#include <gtk/gtk.h>
#include "proc_net.h"

G_BEGIN_DECLS
#define YD_TYPE_TCP_DETAIL (yd_tcp_detail_get_type ())
#define YD_TCP_DETAIL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YD_TYPE_TCP_DETAIL, YdTcpDetail))
#define YD_TCP_DETAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YD_TYPE_TCP_DETAIL, YdTcpDetailClass))
#define YD_IS_TCP_DETAIL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YD_TYPE_TCP_DETAIL))
#define YD_IS_TCP_DETAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YD_TYPE_TCP_DETAIL))
#define YD_TCP_DETAIL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YD_TYPE_TCP_DETAIL, YdTcpDetailClass))
typedef struct _YdTcpDetail YdTcpDetail;
typedef struct _YdTcpDetailClass YdTcpDetailClass;
typedef struct _YdTcpDetailPrivate YdTcpDetailPrivate;

struct _YdTcpDetail {
    GtkDialog parent_instance;
    YdTcpDetailPrivate *priv;
};

struct _YdTcpDetailClass {
    GtkDialogClass parent_class;
};


GType yd_tcp_detail_get_type(void) G_GNUC_CONST;
YdTcpDetail *yd_tcp_detail_new(void);
YdTcpDetail *yd_tcp_detail_construct(GType object_type);
void yd_tcp_detail_show_dialog(YdTcpDetail * self);

void yd_tcp_detail_update(YdTcpDetail * self, ProcNetTcpEntry * tcp);


G_END_DECLS
#endif
